cicd: 애플리케이션을 실행에 실패하면 종료 코드를 1로 변경해 git actions step이 실패하도록 변경

diff --git a/.github/workflows/backend-cd-dev.yml b/.github/workflows/backend-cd-dev.yml
--- a/.github/workflows/backend-cd-dev.yml
+++ b/.github/workflows/backend-cd-dev.yml
@@ -4,6 +4,8 @@ on:
   push:
     branches: [ backend ]
     paths: [ 'backend/**' ]
+  pull_request:
+    branches: [ backend ]
   workflow_dispatch:
 
 jobs:
@@ -105,5 +107,7 @@ jobs:
             echo "Application started with PID: $NEW_WAS_PID."
           else
             echo "Error: Application failed to start."
+            # git action failed 처리
+            exit 1
           fi
           echo "Deployment complete."
