[BE] dev cd 파이프라인 실패하더라도 git actions는 성공하는 문제 (#666)
* cicd: 애플리케이션을 실행에 실패하면 종료 코드를 1로 변경해 git actions step이 실패하도록 변경

* cicd: 디버깅용 트리거 제거

diff --git a/.github/workflows/backend-cd-dev.yml b/.github/workflows/backend-cd-dev.yml
--- a/.github/workflows/backend-cd-dev.yml
+++ b/.github/workflows/backend-cd-dev.yml
@@ -105,5 +105,7 @@ jobs:
             echo "Application started with PID: $NEW_WAS_PID."
           else
             echo "Error: Application failed to start."
+            # git action failed 처리
+            exit 1
           fi
           echo "Deployment complete."
